### ISSUE TITLE
List the available search fields below search box [ACAD #16]

### ISSUE THREAD

**Issue by Li-ReDBox** [acadsamplesdb/acad_samples#25]
Enhancement ID 16:

User without previous experience can search against indexed key words in a format of:
e.g. common_name: country:

**Comment by sgoodswen** [comment]
The enhancement is to List the available search fields below the search box e.g. 

Search keywords (e.g. acad_num:17 to find ACAD # 17)

acad_num other_num group common_name genus species subspecies category extracted_by_date
acad_location date_of_entry abc_num description region country state locallity location
lat lon datum collection_date collected_by quality museum museum_num sampled_by sample_date
mismatch_reason sample_repat Import permit #

**Comment by Li-ReDBox** [comment]
@sgoodswen, do you have any styling requirement? I found the place to change and minimal work has been done. You can go to dev site have a look.

**Comment by sgoodswen** [comment]
Looks good except Import, permit, # is actually one field "Import permit #". However, this search does not work because of the spaces (see issue #14 but Carbon date no longer required).

I think the style might  be clearer if "(e.g. acad_num:17 to find ACAD # 17)" is removed and examples are added beneath the keywords after a line space. e.g.

...
mismatch_reason, sample_repat ,Import permit #

Examples

List the sample with the ACAD number 20. Enter:
acad_num:20

List all samples containing the common name Bison. Enter: 
common_name:Bison

List all samples containing Bison in any field. Enter:
Bison

List all samples containing Bison or Pig in any field. Enter:
bison OR pig

List all samples containing Bison and Russia in any field. Enter:
Bison AND Russia

List all samples from the country Russia with the category Bone. Enter:
country:russia category:bone

**Comment by Li-ReDBox** [comment]
@sgoodswen: I have updated it with your examples and removed "(e.g. acad_num:17 to find ACAD # 17)".  Let me know what you think.

Has this issue been closed?

**Comment by sgoodswen** [comment]
The display looks good especially the examples highlighted in red

This issue can be closed
